/**
 * Generated by tsnapi — public API snapshot of `cli` */
// Interfaces
export interface DoctorDiagnostics {
  cli: {
    name: string;
    version: string;
    executable: string;
  };
  runtime: {
    node: string;
    platform: string;
    arch: string;
    shell: string;
    packageManager: string;
  };
  system: {
    os: string;
    cwd: string;
  };
  config: {
    path: string;
    keys: string[];
  };
}

// Functions
export declare function add(_: number, _: number): number;
export declare function buildDoctorDiagnostics(_: {
  pkg: {
    name: string;
    version: string;
  };
  executable: string;
  node: string;
  platform: string;
  arch: string;
  shell: string;
  packageManager: string;
  osType: string;
  osRelease: string;
  cwd: string;
  configPath: string;
  configStoreKeys: string[];
}): DoctorDiagnostics;
export declare function collectDoctorDiagnostics(_?: CollectDoctorDiagnosticsOptions): DoctorDiagnostics;
export declare function doctorDiagnosticsTableRows(_: DoctorDiagnostics): [string, string][];
export declare function formatDoctorDiagnosticsJson(_: DoctorDiagnostics): string;